CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  done BOOLEAN DEFAULT FALSE
);

-- Dummy data generated by Gemini
INSERT INTO tasks (title, done) VALUES 
('Buy groceries', false),
('Finish CS 315 assignment', false),
('Review Docker concepts', true),
('Call Mom', false),
('Gym session', true),
('Prepare for thesis presentation', false),
('Email professor about research', false),
('Organize desk', true),
('Read documentation on Postgres', false),
('Update portfolio website', false);